### ISSUE TITLE
Migration Failed

### ISSUE THREAD

**Issue by darrylmorley** [cloudverve/wp-sync-db#4]
Hi,

I am getting a Migration failed notification. The error reported is 

```
WordPress database error: [Duplicate foreign key constraint name 'fk_wp_wc_download_log_permission_id']
ALTER TABLE `wp_wc_download_log` ADD CONSTRAINT `fk_wp_wc_download_log_permission_id` FOREIGN KEY (`permission_id`) REFERENCES `wp_woocommerce_downloadable_product_permissions` (`permission_id`) ON DELETE CASCADE
```
Could anyone advise how to resolve please?

**Comment by degregar** [comment]
@darrylmorley I'm facing the same issue. Can you tell me why did you close the issue? Did you solve it somehow?

**Comment by darrylmorley** [comment]
@degregar I closed my issue because this is no longer in development, this was unlikely to be addressed. 

I also switched to another solution from 10up. https://10up.com/blog/2017/wp-snapshots-share-wordpress-setup/
